# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BusTrafficDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BusTrafficDemo

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'SVProgressHUD'
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.7'
pod 'SwiftyJSON', '~> 4.0'
pod 'ARCL'
pod 'Fabric'
pod 'Crashlytics'

end
